spring:
  application:
    name: HousingManagementSystem

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret-key: ${JWT_SECRET:super-secret-key-change-me}
  access-token-expiration: 900000                     #15 mins(in ms)
  refresh-token-expiration: 604800000                #7 days(in ms)
